/* Generated by tools/build_exercises.py. Do not edit by hand.
   Source: github.com/hasaneyldrm/exercises-dataset (data: MIT).
   Media: © Gym visual (gymvisual.com), loaded from the dataset repo, not redistributed. */
window.MEDIA_BASE = "https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/7455efae41b330c265e7cd4b78dfa848e7ce5ebd/";
window.EXERCISES = {
 "0017": {
  "name": "assisted pull-up",
  "target": "lats",
  "secondary": [
   "biceps",
   "forearms"
  ],
  "equipment": "leverage machine",
  "bodyPart": "back",
  "steps": [
   "Adjust the machine to your desired weight and height settings.",
   "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
   "Hang with your arms fully extended and your feet off the ground.",
   "Engage your back muscles and pull your body up towards the handles, keeping your elbows close to your body.",
   "Continue pulling until your chin is above the handles.",
   "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0017-kiJ4Z2K.gif",
  "img": "images/0017-kiJ4Z2K.jpg"
 },
 "0025": {
  "name": "barbell bench press",
  "target": "pectorals",
  "secondary": [
   "triceps",
   "shoulders"
  ],
  "equipment": "barbell",
  "bodyPart": "chest",
  "steps": [
   "Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.",
   "Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.",
   "Lift the barbell off the rack and hold it directly above your chest with your arms fully extended.",
   "Lower the barbell slowly towards your chest, keeping your elbows tucked in.",
   "Pause for a moment when the barbell touches your chest.",
   "Push the barbell back up to the starting position by extending your arms.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0025-EIeI8Vf.gif",
  "img": "images/0025-EIeI8Vf.jpg"
 },
 "0027": {
  "name": "barbell bent over row",
  "target": "upper back",
  "secondary": [
   "biceps",
   "forearms"
  ],
  "equipment": "barbell",
  "bodyPart": "back",
  "steps": [
   "Stand with your feet shoulder-width apart and knees slightly bent.",
   "Bend forward at the hips while keeping your back straight and chest up.",
   "Grasp the barbell with an overhand grip, hands slightly wider than shoulder-width apart.",
   "Pull the barbell towards your lower chest by retracting your shoulder blades and squeezing your back muscles.",
   "Pause for a moment at the top, then slowly lower the barbell back to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0027-eZyBC3j.gif",
  "img": "images/0027-eZyBC3j.jpg"
 },
 "0043": {
  "name": "barbell full squat",
  "target": "glutes",
  "secondary": [
   "quadriceps",
   "hamstrings",
   "calves",
   "core"
  ],
  "equipment": "barbell",
  "bodyPart": "upper legs",
  "steps": [
   "Stand with your feet shoulder-width apart, toes slightly turned out.",
   "Hold the barbell across your upper back, resting it on your traps or rear delts.",
   "Engage your core and keep your chest up as you begin to lower your body down.",
   "Bend at the knees and hips, pushing your hips back and down as if sitting into a chair.",
   "Lower yourself until your thighs are parallel to the ground or slightly below.",
   "Keep your knees in line with your toes and your weight in your heels.",
   "Drive through your heels to stand back up, extending your hips and knees.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0043-qXTaZnJ.gif",
  "img": "images/0043-qXTaZnJ.jpg"
 },
 "0060": {
  "name": "barbell lying triceps extension skull crusher",
  "target": "triceps",
  "secondary": [
   "shoulders"
  ],
  "equipment": "barbell",
  "bodyPart": "upper arms",
  "steps": [
   "Lie flat on a bench with your feet flat on the ground and your head at the end of the bench.",
   "Hold the barbell with an overhand grip, hands shoulder-width apart, and extend your arms straight up over your chest.",
   "Keeping your upper arms stationary, slowly lower the barbell towards your forehead by bending your elbows.",
   "Pause for a moment when the barbell is just above your forehead, then extend your arms back up to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0060-h8LFzo9.gif",
  "img": "images/0060-h8LFzo9.jpg"
 },
 "0150": {
  "name": "cable bar lateral pulldown",
  "target": "lats",
  "secondary": [
   "biceps",
   "rhomboids",
   "rear deltoids"
  ],
  "equipment": "cable",
  "bodyPart": "back",
  "steps": [
   "Adjust the cable pulley to a high position and attach a straight bar.",
   "Sit facing the cable machine with your feet flat on the ground and your knees slightly bent.",
   "Grasp the bar with an overhand grip, slightly wider than shoulder-width apart.",
   "Lean back slightly and keep your chest up, maintaining a slight arch in your lower back.",
   "Pull the bar down towards your chest, leading with your elbows and squeezing your shoulder blades together.",
   "Pause for a moment at the bottom of the movement, then slowly return the bar to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0150-eYnzaCm.gif",
  "img": "images/0150-eYnzaCm.jpg"
 },
 "0165": {
  "name": "cable hammer curl (with rope)",
  "target": "biceps",
  "secondary": [
   "forearms"
  ],
  "equipment": "cable",
  "bodyPart": "upper arms",
  "steps": [
   "Stand upright with your feet shoulder-width apart and a slight bend in your knees.",
   "Hold the cable rope attachment with an underhand grip, palms facing each other, and your arms fully extended.",
   "Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.",
   "Continue to raise the cable rope attachment until your biceps are fully contracted and the rope is at shoulder level.",
   "Hold the contracted position for a brief pause as you squeeze your biceps.",
   "Inhale and slowly begin to lower the cable rope attachment back to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0165-HPlPoQA.gif",
  "img": "images/0165-HPlPoQA.jpg"
 },
 "0175": {
  "name": "cable kneeling crunch",
  "target": "abs",
  "secondary": [
   "obliques"
  ],
  "equipment": "cable",
  "bodyPart": "waist",
  "steps": [
   "Attach a rope handle to a high pulley and kneel down facing away from the machine.",
   "Hold the rope handle with both hands and place it behind your head, keeping your elbows out to the sides.",
   "Keeping your hips stationary, flex your waist and crunch your torso down towards your thighs.",
   "Pause for a moment at the bottom, then slowly return to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0175-WW95auq.gif",
  "img": "images/0175-WW95auq.jpg"
 },
 "0178": {
  "name": "cable lateral raise",
  "target": "delts",
  "secondary": [
   "traps",
   "triceps"
  ],
  "equipment": "cable",
  "bodyPart": "shoulders",
  "steps": [
   "Stand with your feet shoulder-width apart and grasp the cable handles with an overhand grip.",
   "Keep your arms straight and your core engaged.",
   "Raise your arms out to the sides until they are parallel to the floor.",
   "Pause for a moment at the top, then slowly lower your arms back down to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0178-goJ6ezq.gif",
  "img": "images/0178-goJ6ezq.jpg"
 },
 "0194": {
  "name": "cable overhead triceps extension (rope attachment)",
  "target": "triceps",
  "secondary": [
   "shoulders"
  ],
  "equipment": "cable",
  "bodyPart": "upper arms",
  "steps": [
   "Attach a rope to a cable machine at a high position.",
   "Stand facing away from the machine with your feet shoulder-width apart.",
   "Grasp the rope with both hands, palms facing each other, and bring your hands above your head.",
   "Keep your upper arms close to your head and your elbows pointing forward.",
   "Slowly lower the rope behind your head by bending your elbows.",
   "Pause for a moment, then extend your arms back up to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0194-2IxROQ1.gif",
  "img": "images/0194-2IxROQ1.jpg"
 },
 "0200": {
  "name": "cable pushdown (with rope attachment)",
  "target": "triceps",
  "secondary": [
   "forearms"
  ],
  "equipment": "cable",
  "bodyPart": "upper arms",
  "steps": [
   "Attach a rope attachment to a high pulley on a cable machine.",
   "Stand facing the machine with your feet shoulder-width apart and a slight bend in your knees.",
   "Grasp the rope with an overhand grip, palms facing each other.",
   "Keep your elbows close to your sides and your upper arms stationary throughout the exercise.",
   "Exhale and push the rope downward by extending your elbows until your arms are fully extended.",
   "Pause for a moment, then inhale and slowly return to the starting position by allowing your elbows to flex.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0200-dU605di.gif",
  "img": "images/0200-dU605di.jpg"
 },
 "0203": {
  "name": "cable rear delt row (with rope)",
  "target": "delts",
  "secondary": [
   "trapezius",
   "rhomboids",
   "biceps"
  ],
  "equipment": "cable",
  "bodyPart": "shoulders",
  "steps": [
   "Attach a rope handle to a low pulley cable machine.",
   "Stand facing the machine with your feet shoulder-width apart.",
   "Grasp the rope handle with an overhand grip, palms facing each other.",
   "Bend your knees slightly and hinge forward at the hips, keeping your back straight.",
   "Keep your elbows slightly bent and pull the rope towards your chest, squeezing your shoulder blades together.",
   "Pause for a moment at the top of the movement, then slowly release the tension and return to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0203-wqNPGCg.gif",
  "img": "images/0203-wqNPGCg.jpg"
 },
 "0227": {
  "name": "cable standing fly",
  "target": "pectorals",
  "secondary": [
   "deltoids",
   "triceps"
  ],
  "equipment": "cable",
  "bodyPart": "chest",
  "steps": [
   "Attach the handles to the cables at chest height.",
   "Stand with your feet shoulder-width apart, facing away from the cable machine.",
   "Grasp the handles with an overhand grip, palms facing forward.",
   "Step forward slightly to create tension in the cables.",
   "Keep your core engaged and your back straight throughout the exercise.",
   "With a slight bend in your elbows, slowly bring your arms forward and together in front of your chest.",
   "Squeeze your chest muscles at the peak of the movement.",
   "Slowly reverse the movement, returning your arms to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0227-Pr9Rhf4.gif",
  "img": "images/0227-Pr9Rhf4.jpg"
 },
 "0241": {
  "name": "cable triceps pushdown (v-bar)",
  "target": "triceps",
  "secondary": [
   "forearms"
  ],
  "equipment": "cable",
  "bodyPart": "upper arms",
  "steps": [
   "Attach a v-bar attachment to the cable machine at the highest setting.",
   "Stand facing the cable machine with your feet shoulder-width apart.",
   "Grasp the v-bar with an overhand grip, palms facing down, and your hands shoulder-width apart.",
   "Keep your elbows close to your sides and your upper arms stationary throughout the exercise.",
   "Engage your triceps and exhale as you push the v-bar down until your arms are fully extended.",
   "Pause for a moment at the bottom of the movement, squeezing your triceps.",
   "Inhale as you slowly return the v-bar to the starting position, maintaining control.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0241-gAwDzB3.gif",
  "img": "images/0241-gAwDzB3.jpg"
 },
 "0289": {
  "name": "dumbbell bench press",
  "target": "pectorals",
  "secondary": [
   "triceps",
   "shoulders"
  ],
  "equipment": "dumbbell",
  "bodyPart": "chest",
  "steps": [
   "Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.",
   "Hold a dumbbell in each hand, with your palms facing forward and your arms extended above your chest.",
   "Lower the dumbbells slowly to the sides of your chest, keeping your elbows at a 90-degree angle.",
   "Pause for a moment, then push the dumbbells back up to the starting position, fully extending your arms.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0289-SpYC0Kp.gif",
  "img": "images/0289-SpYC0Kp.jpg"
 },
 "0292": {
  "name": "dumbbell one arm bent-over row",
  "target": "upper back",
  "secondary": [
   "biceps",
   "forearms"
  ],
  "equipment": "dumbbell",
  "bodyPart": "back",
  "steps": [
   "Stand with your feet shoulder-width apart, holding a dumbbell in one hand with your palm facing your body.",
   "Bend your knees slightly and hinge forward at the hips, keeping your back straight and your core engaged.",
   "Let the dumbbell hang straight down towards the floor, with your arm fully extended.",
   "Pull the dumbbell up towards your chest, keeping your elbow close to your body and squeezing your shoulder blades together.",
   "Pause for a moment at the top, then slowly lower the dumbbell back down to the starting position.",
   "Repeat for the desired number of repetitions, then switch sides."
  ],
  "gif": "videos/0292-C0MA9bC.gif",
  "img": "images/0292-C0MA9bC.jpg"
 },
 "0294": {
  "name": "dumbbell biceps curl",
  "target": "biceps",
  "secondary": [
   "forearms"
  ],
  "equipment": "dumbbell",
  "bodyPart": "upper arms",
  "steps": [
   "Stand up straight with a dumbbell in each hand, palms facing forward and arms fully extended.",
   "Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.",
   "Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.",
   "Hold the contracted position for a brief pause as you squeeze your biceps.",
   "Inhale and slowly begin to lower the dumbbells back to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0294-NbVPDMW.gif",
  "img": "images/0294-NbVPDMW.jpg"
 },
 "0313": {
  "name": "dumbbell hammer curl",
  "target": "biceps",
  "secondary": [
   "forearms"
  ],
  "equipment": "dumbbell",
  "bodyPart": "upper arms",
  "steps": [
   "Stand up straight with a dumbbell in each hand, palms facing your torso.",
   "Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward.",
   "This will be your starting position.",
   "Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps.",
   "Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.",
   "Hold the contracted position for a brief pause as you squeeze your biceps.",
   "Then, inhale and slowly begin to lower the dumbbells back to the starting position.",
   "Repeat for the recommended amount of repetitions."
  ],
  "gif": "videos/0313-slDvUAU.gif",
  "img": "images/0313-slDvUAU.jpg"
 },
 "0314": {
  "name": "dumbbell incline bench press",
  "target": "pectorals",
  "secondary": [
   "shoulders",
   "triceps"
  ],
  "equipment": "dumbbell",
  "bodyPart": "chest",
  "steps": [
   "Set up an incline bench at a 45-degree angle.",
   "Sit on the bench with your feet flat on the ground and your back pressed firmly against the bench.",
   "Hold a dumbbell in each hand, palms facing forward, and lift them to shoulder height.",
   "Slowly lower the dumbbells to the sides of your chest, keeping your elbows at a 90-degree angle.",
   "Push the dumbbells back up to the starting position, fully extending your arms.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0314-ns0SIbU.gif",
  "img": "images/0314-ns0SIbU.jpg"
 },
 "0334": {
  "name": "dumbbell lateral raise",
  "target": "delts",
  "secondary": [
   "traps"
  ],
  "equipment": "dumbbell",
  "bodyPart": "shoulders",
  "steps": [
   "Stand with your feet shoulder-width apart and hold a dumbbell in each hand, palms facing your body.",
   "Keep your back straight and engage your core.",
   "Raise your arms out to the sides until they are parallel to the floor, keeping a slight bend in your elbows.",
   "Pause for a moment at the top, then slowly lower your arms back down to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0334-DsgkuIt.gif",
  "img": "images/0334-DsgkuIt.jpg"
 },
 "0336": {
  "name": "dumbbell lunge",
  "target": "glutes",
  "secondary": [
   "quadriceps",
   "hamstrings",
   "calves"
  ],
  "equipment": "dumbbell",
  "bodyPart": "upper legs",
  "steps": [
   "Stand with your feet shoulder-width apart, holding a dumbbell in each hand.",
   "Take a step forward with your right foot, lowering your body into a lunge position.",
   "Keep your back straight and your chest up as you lower your body.",
   "Push through your right heel to return to the starting position.",
   "Repeat with your left leg.",
   "Alternate legs for the desired number of repetitions."
  ],
  "gif": "videos/0336-RRWFUcw.gif",
  "img": "images/0336-RRWFUcw.jpg"
 },
 "0405": {
  "name": "dumbbell seated shoulder press",
  "target": "delts",
  "secondary": [
   "triceps",
   "upper back"
  ],
  "equipment": "dumbbell",
  "bodyPart": "shoulders",
  "steps": [
   "Sit on a bench with a dumbbell in each hand, resting on your thighs.",
   "Raise the dumbbells to shoulder height, palms facing forward.",
   "Press the dumbbells upward until your arms are fully extended overhead.",
   "Pause for a moment at the top, then slowly lower the dumbbells back to shoulder height.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0405-znQUdHY.gif",
  "img": "images/0405-znQUdHY.jpg"
 },
 "0410": {
  "name": "dumbbell single leg split squat",
  "target": "quads",
  "secondary": [
   "glutes",
   "hamstrings",
   "calves"
  ],
  "equipment": "dumbbell",
  "bodyPart": "upper legs",
  "steps": [
   "Stand with your feet shoulder-width apart, holding a dumbbell in each hand.",
   "Take a step forward with one foot and position your feet so that your front foot is flat on the ground and your back foot is elevated on a bench or step.",
   "Lower your body by bending your front knee and hip, keeping your back knee slightly bent and your back heel off the ground.",
   "Continue lowering until your front thigh is parallel to the ground, then push through your front heel to return to the starting position.",
   "Repeat for the desired number of repetitions, then switch legs and repeat."
  ],
  "gif": "videos/0410-qx4fgX7.gif",
  "img": "images/0410-qx4fgX7.jpg"
 },
 "0447": {
  "name": "ez barbell curl",
  "target": "biceps",
  "secondary": [
   "forearms"
  ],
  "equipment": "ez barbell",
  "bodyPart": "upper arms",
  "steps": [
   "Stand up straight with your feet shoulder-width apart and hold the ez barbell with an underhand grip, palms facing up.",
   "Keep your elbows close to your torso and your upper arms stationary throughout the movement.",
   "Exhale as you curl the barbell up towards your shoulders, contracting your biceps.",
   "Pause for a moment at the top, then inhale as you slowly lower the barbell back down to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0447-6TG6x2w.gif",
  "img": "images/0447-6TG6x2w.jpg"
 },
 "0472": {
  "name": "hanging leg raise",
  "target": "abs",
  "secondary": [
   "hip flexors"
  ],
  "equipment": "body weight",
  "bodyPart": "waist",
  "steps": [
   "Hang from a pull-up bar with your arms fully extended and your palms facing away from you.",
   "Engage your core and lift your legs up in front of you, keeping them straight.",
   "Continue lifting until your legs are parallel to the ground or as high as you can comfortably go.",
   "Pause for a moment at the top, then slowly lower your legs back down to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0472-I3tsCnC.gif",
  "img": "images/0472-I3tsCnC.jpg"
 },
 "0577": {
  "name": "lever chest press",
  "target": "pectorals",
  "secondary": [
   "triceps",
   "shoulders"
  ],
  "equipment": "leverage machine",
  "bodyPart": "chest",
  "steps": [
   "Adjust the seat height and position yourself on the machine with your back flat against the pad.",
   "Grasp the handles with an overhand grip and position your elbows at a 90-degree angle.",
   "Push the handles forward until your arms are fully extended, exhaling during the movement.",
   "Pause briefly at the end of the movement, then slowly return to the starting position, inhaling as you do so.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0577-T0yTjgW.gif",
  "img": "images/0577-T0yTjgW.jpg"
 },
 "0585": {
  "name": "lever leg extension",
  "target": "quads",
  "secondary": [
   "hamstrings"
  ],
  "equipment": "leverage machine",
  "bodyPart": "upper legs",
  "steps": [
   "Adjust the seat height and backrest of the machine to fit your body.",
   "Sit on the machine with your back against the backrest and your feet on the footpad.",
   "Grasp the handles or sidebars for stability.",
   "Extend your legs forward by straightening your knees, lifting the weight.",
   "Pause for a moment at the top, then slowly lower the weight back to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0585-my33uHU.gif",
  "img": "images/0585-my33uHU.jpg"
 },
 "0586": {
  "name": "lever lying leg curl",
  "target": "hamstrings",
  "secondary": [
   "calves"
  ],
  "equipment": "leverage machine",
  "bodyPart": "upper legs",
  "steps": [
   "Adjust the machine to fit your body and select the desired weight.",
   "Lie face down on the machine with your legs straight and your heels against the padded lever.",
   "Grasp the handles or the sides of the machine for stability.",
   "Keeping your upper body stationary, exhale and curl your legs up as far as possible without lifting your hips off the pad.",
   "Hold the contracted position for a brief pause as you squeeze your hamstrings.",
   "Inhale and slowly lower the lever back to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0586-17lJ1kr.gif",
  "img": "images/0586-17lJ1kr.jpg"
 },
 "0596": {
  "name": "lever seated fly",
  "target": "pectorals",
  "secondary": [
   "deltoids",
   "trapezius"
  ],
  "equipment": "leverage machine",
  "bodyPart": "chest",
  "steps": [
   "Adjust the seat height and position yourself on the machine with your back against the pad.",
   "Grasp the handles with a pronated grip and keep your elbows slightly bent.",
   "Exhale and push the handles forward, bringing them together in front of your chest.",
   "Pause for a moment, squeezing your chest muscles.",
   "Inhale and slowly return to the starting position, allowing your chest muscles to stretch.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0596-v3xmPAR.gif",
  "img": "images/0596-v3xmPAR.jpg"
 },
 "0599": {
  "name": "lever seated leg curl",
  "target": "hamstrings",
  "secondary": [
   "calves"
  ],
  "equipment": "leverage machine",
  "bodyPart": "upper legs",
  "steps": [
   "Adjust the machine to fit your body and sit on it with your back against the backrest.",
   "Place your lower legs under the padded lever, just above your ankles.",
   "Grasp the handles on the sides of the machine for support.",
   "Keeping your upper legs stationary, exhale and curl your legs up as far as possible.",
   "Hold the contracted position for a brief pause as you squeeze your hamstrings.",
   "Inhale and slowly lower the lever back to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0599-Zg3XY7P.gif",
  "img": "images/0599-Zg3XY7P.jpg"
 },
 "0602": {
  "name": "lever seated reverse fly",
  "target": "delts",
  "secondary": [
   "trapezius",
   "rhomboids"
  ],
  "equipment": "leverage machine",
  "bodyPart": "shoulders",
  "steps": [
   "Adjust the seat height and position yourself on the machine with your chest against the pad and your feet flat on the floor.",
   "Grasp the handles with an overhand grip and keep your arms slightly bent.",
   "Exhale and squeeze your shoulder blades together as you pull the handles back and outward, away from your body.",
   "Pause for a moment at the peak contraction, then inhale and slowly return to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0602-myfUsKf.gif",
  "img": "images/0602-myfUsKf.jpg"
 },
 "0603": {
  "name": "lever shoulder press",
  "target": "delts",
  "secondary": [
   "triceps",
   "chest"
  ],
  "equipment": "leverage machine",
  "bodyPart": "shoulders",
  "steps": [
   "Adjust the seat height and position yourself on the machine with your back against the backrest.",
   "Grasp the handles with an overhand grip and position your hands at shoulder level.",
   "Push the handles upward until your arms are fully extended, but do not lock your elbows.",
   "Pause for a moment at the top, then slowly lower the handles back down to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0603-67n3r98.gif",
  "img": "images/0603-67n3r98.jpg"
 },
 "0605": {
  "name": "lever standing calf raise",
  "target": "calves",
  "secondary": [
   "soleus",
   "ankle stabilizers"
  ],
  "equipment": "leverage machine",
  "bodyPart": "lower legs",
  "steps": [
   "Adjust the machine to your height and stand with your feet shoulder-width apart.",
   "Place your shoulders under the pads and hold onto the handles for stability.",
   "Raise your heels as high as possible by extending your ankles.",
   "Pause for a moment at the top, then slowly lower your heels back down to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0605-ykUOVze.gif",
  "img": "images/0605-ykUOVze.jpg"
 },
 "0652": {
  "name": "pull-up",
  "target": "lats",
  "secondary": [
   "biceps",
   "forearms"
  ],
  "equipment": "body weight",
  "bodyPart": "back",
  "steps": [
   "Hang from a pull-up bar with your palms facing away from you and your arms fully extended.",
   "Engage your core and squeeze your shoulder blades together.",
   "Pull your body up towards the bar by bending your elbows and bringing your chest towards the bar.",
   "Pause at the top of the movement, then slowly lower your body back down to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0652-lBDjFxJ.gif",
  "img": "images/0652-lBDjFxJ.jpg"
 },
 "0743": {
  "name": "sled hack squat",
  "target": "glutes",
  "secondary": [
   "quadriceps",
   "hamstrings",
   "calves"
  ],
  "equipment": "sled machine",
  "bodyPart": "upper legs",
  "steps": [
   "Adjust the sled machine to a comfortable position for your height.",
   "Stand with your feet shoulder-width apart on the platform, toes slightly pointed outwards.",
   "Hold onto the handles or bars for stability.",
   "Lower your body by bending your knees and hips, keeping your back straight and chest up.",
   "Continue lowering until your thighs are parallel to the ground or slightly below.",
   "Pause for a moment, then push through your heels to raise your body back up to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0743-Qa55kX1.gif",
  "img": "images/0743-Qa55kX1.jpg"
 },
 "0757": {
  "name": "smith incline bench press",
  "target": "pectorals",
  "secondary": [
   "shoulders",
   "triceps"
  ],
  "equipment": "smith machine",
  "bodyPart": "chest",
  "steps": [
   "Adjust the bench to a 30-45 degree incline.",
   "Sit on the bench with your back flat against the pad and feet firmly on the ground.",
   "Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.",
   "Unrack the barbell and lower it slowly towards your upper chest, keeping your elbows slightly tucked in.",
   "Pause for a moment at the bottom, then push the barbell back up to the starting position, fully extending your arms.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0757-5v7KYld.gif",
  "img": "images/0757-5v7KYld.jpg"
 },
 "0818": {
  "name": "twin handle parallel grip lat pulldown",
  "target": "lats",
  "secondary": [
   "biceps",
   "rhomboids",
   "rear deltoids"
  ],
  "equipment": "cable",
  "bodyPart": "back",
  "steps": [
   "Adjust the seat height and position yourself facing the cable machine.",
   "Grasp the handles with an overhand grip, hands shoulder-width apart.",
   "Sit down and position your thighs under the thigh pads, keeping your feet flat on the floor.",
   "Lean back slightly and keep your chest up, maintaining a neutral spine.",
   "Pull the handles down towards your upper chest, squeezing your shoulder blades together.",
   "Pause for a moment at the bottom of the movement, feeling the contraction in your lats.",
   "Slowly release the handles and return to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0818-rkg41Fb.gif",
  "img": "images/0818-rkg41Fb.jpg"
 },
 "0861": {
  "name": "cable seated row",
  "target": "upper back",
  "secondary": [
   "biceps",
   "forearms"
  ],
  "equipment": "cable",
  "bodyPart": "back",
  "steps": [
   "Sit on the cable row machine with your feet flat on the footrests and your knees slightly bent.",
   "Grasp the handles with an overhand grip, keeping your back straight and your shoulders relaxed.",
   "Pull the handles towards your body, squeezing your shoulder blades together.",
   "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0861-fUBheHs.gif",
  "img": "images/0861-fUBheHs.jpg"
 },
 "0868": {
  "name": "cable curl",
  "target": "biceps",
  "secondary": [
   "forearms"
  ],
  "equipment": "cable",
  "bodyPart": "upper arms",
  "steps": [
   "Stand facing the cable machine with your feet shoulder-width apart.",
   "Grasp the cable attachment with an underhand grip, palms facing up.",
   "Keep your elbows close to your sides and your upper arms stationary.",
   "Exhale and curl the cable attachment towards your shoulders, contracting your biceps.",
   "Pause for a moment at the top of the movement, squeezing your biceps.",
   "Inhale and slowly lower the cable attachment back to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0868-G08RZcQ.gif",
  "img": "images/0868-G08RZcQ.jpg"
 },
 "0872": {
  "name": "reverse crunch",
  "target": "abs",
  "secondary": [
   "hip flexors"
  ],
  "equipment": "body weight",
  "bodyPart": "waist",
  "steps": [
   "Lie flat on your back with your arms extended along your sides.",
   "Bend your knees and lift your feet off the ground, bringing your thighs perpendicular to the floor.",
   "Contract your abs and curl your hips off the floor, bringing your knees towards your chest.",
   "Pause for a moment at the top, then slowly lower your hips back down to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/0872-nCU1Ekp.gif",
  "img": "images/0872-nCU1Ekp.jpg"
 },
 "1350": {
  "name": "lever seated row",
  "target": "upper back",
  "secondary": [
   "biceps",
   "forearms"
  ],
  "equipment": "leverage machine",
  "bodyPart": "back",
  "steps": [
   "Adjust the seat height and footrests to a comfortable position.",
   "Sit on the machine with your chest against the pad and your feet on the footrests.",
   "Grasp the handles with an overhand grip, shoulder-width apart.",
   "Keep your back straight and your core engaged.",
   "Pull the handles towards your body, squeezing your shoulder blades together.",
   "Pause for a moment at the peak of the movement.",
   "Slowly release the handles and return to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/1350-7I6LNUG.gif",
  "img": "images/1350-7I6LNUG.jpg"
 },
 "1391": {
  "name": "sled calf press on leg press",
  "target": "calves",
  "secondary": [
   "hamstrings",
   "quadriceps"
  ],
  "equipment": "sled machine",
  "bodyPart": "lower legs",
  "steps": [
   "Adjust the seat of the leg press machine so that your knees are slightly bent when your feet are on the sled.",
   "Place your feet shoulder-width apart on the sled, with your toes pointing forward.",
   "Release the safety handles and push the sled away from you by extending your knees and ankles.",
   "Pause for a moment at the top of the movement, then slowly lower the sled back down by bending your knees and ankles.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/1391-ykHcWme.gif",
  "img": "images/1391-ykHcWme.jpg"
 },
 "1456": {
  "name": "barbell standing close grip military press",
  "target": "delts",
  "secondary": [
   "triceps",
   "upper back"
  ],
  "equipment": "barbell",
  "bodyPart": "shoulders",
  "steps": [
   "Stand with your feet shoulder-width apart and hold the barbell with an overhand grip, hands slightly closer than shoulder-width apart.",
   "Lift the barbell to shoulder height, keeping your elbows close to your body.",
   "Press the barbell overhead, extending your arms fully.",
   "Lower the barbell back to shoulder height.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/1456-wdRZISl.gif",
  "img": "images/1456-wdRZISl.jpg"
 },
 "1463": {
  "name": "sled 45° leg press (side pov)",
  "target": "glutes",
  "secondary": [
   "quadriceps",
   "hamstrings",
   "calves"
  ],
  "equipment": "sled machine",
  "bodyPart": "upper legs",
  "steps": [
   "Adjust the seat of the sled machine so that your knees are at a 90-degree angle when your feet are on the footplate.",
   "Sit on the sled machine with your back flat against the backrest and your feet shoulder-width apart on the footplate.",
   "Grip the handles on the sides of the seat for stability.",
   "Push against the footplate to extend your legs, straightening them completely.",
   "Pause for a moment at the top, then slowly bend your knees to lower the footplate back to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/1463-2Qh2J1e.gif",
  "img": "images/1463-2Qh2J1e.jpg"
 },
 "1760": {
  "name": "dumbbell goblet squat",
  "target": "quads",
  "secondary": [
   "glutes",
   "hamstrings",
   "calves"
  ],
  "equipment": "dumbbell",
  "bodyPart": "upper legs",
  "steps": [
   "Stand with your feet shoulder-width apart, holding a dumbbell vertically against your chest with both hands.",
   "Keeping your chest up and core engaged, lower your body down into a squat position by pushing your hips back and bending your knees.",
   "Continue lowering until your thighs are parallel to the ground, or as low as you can comfortably go.",
   "Pause for a moment at the bottom, then push through your heels to return to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/1760-yn8yg1r.gif",
  "img": "images/1760-yn8yg1r.jpg"
 },
 "3281": {
  "name": "smith full squat",
  "target": "glutes",
  "secondary": [
   "quadriceps",
   "hamstrings",
   "calves"
  ],
  "equipment": "smith machine",
  "bodyPart": "upper legs",
  "steps": [
   "Set up the smith machine with the barbell at shoulder height.",
   "Stand with your feet shoulder-width apart, toes slightly turned out.",
   "Step under the bar and position it across your upper back, resting on your traps.",
   "Grip the bar with your hands slightly wider than shoulder-width apart.",
   "Unrack the bar and take a step back, maintaining a stable stance.",
   "Keeping your chest up and core engaged, initiate the squat by pushing your hips back and bending your knees.",
   "Lower your body until your thighs are parallel to the ground, or as low as your flexibility allows.",
   "Pause for a moment at the bottom, then drive through your heels to return to the starting position.",
   "Repeat for the desired number of repetitions."
  ],
  "gif": "videos/3281-NNoHCEA.gif",
  "img": "images/3281-NNoHCEA.jpg"
 }
};
