#!/usr/bin/env python3
"""Generate js/exercises.js from the hasaneyldrm/exercises-dataset JSON.

Only the exercises referenced in js/program.js are exported. Media (GIF/JPG)
is NOT copied: the app loads it from the dataset repo (pinned commit) and
caches it on the phone for offline use.

Usage:
    python3 tools/build_exercises.py path/to/exercises.json [commit_sha]
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SHA = "7455efae41b330c265e7cd4b78dfa848e7ce5ebd"


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    src = Path(sys.argv[1])
    sha = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_SHA
    program = (ROOT / "js" / "program.js").read_text(encoding="utf-8")
    ids = sorted(set(re.findall(r"'(\d{4})'", program)))

    data = {x["id"]: x for x in json.loads(src.read_text(encoding="utf-8"))}
    missing = [i for i in ids if i not in data]
    if missing:
        sys.exit(f"IDs not found in dataset: {missing}")

    out = {}
    for i in ids:
        x = data[i]
        steps = x.get("instruction_steps", {}).get("en") or [x["instructions"]["en"]]
        out[i] = {
            "name": x["name"],
            "target": x["target"],
            "secondary": x.get("secondary_muscles", []),
            "equipment": x["equipment"],
            "bodyPart": x["body_part"],
            "steps": [s.strip() for s in steps if s.strip()],
            "gif": x["gif_url"],
            "img": x["image"],
        }

    base = f"https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/{sha}/"
    js = (
        "/* Generated by tools/build_exercises.py. Do not edit by hand.\n"
        "   Source: github.com/hasaneyldrm/exercises-dataset (data: MIT).\n"
        "   Media: © Gym visual (gymvisual.com), loaded from the dataset repo, not redistributed. */\n"
        f"window.MEDIA_BASE = {json.dumps(base)};\n"
        f"window.EXERCISES = {json.dumps(out, ensure_ascii=False, indent=1)};\n"
    )
    (ROOT / "js" / "exercises.js").write_text(js, encoding="utf-8")
    print(f"Wrote {len(out)} exercises to js/exercises.js (media base {base})")


if __name__ == "__main__":
    main()
